### ISSUE TITLE
SharedPreferencesを使用した言語設定管理

### ISSUE THREAD

**Issue by Haru-Kobayashi073** [KDG-Develop-Hub/social-mobile#13]
アプリ起動時に毎回英語圏の人が英語設定にしなおすのはUXがよくない
のでローカルストレージを参照・上書きするなどして、アプリが消されない限り、設定しなおしを無くす

1. 初回起動時にSharedPreferencesで言語設定を保存・言語切り替え時にSharedPreferencesで言語設定を上書き
2. 初回以降の起動時にSharedPreferencesで言語設定を取得し、言語設定を適用する。

globalなstateとしてSharedPreferencesのクラスを使用できるようにお願い！

**Comment by aoiorio** [comment]
![LGTM](https://image.lgtmoon.dev/226032)
