### ISSUE TITLE
BottomNavigationBarの実装

### ISSUE THREAD

**Issue by Haru-Kobayashi073** [KDG-Develop-Hub/social-mobile#5]
Routingの設定なども必要になる
Svgは基本Figmaから落とし、Genでdartコードにコンバートする

[参考Figma](https://www.figma.com/design/feJkoD1AFJ6NXsBEQ5xqF9/app?node-id=1565-1156&t=Hqt9aKKvRMFxr0f1-1)

**Comment by Haru-Kobayashi073** [comment]
基本的にGoRouterを使用する予定

**Comment by kiichi7580** [comment]
> 基本的にGoRouterを使用する予定

使ったことないけど、やってみるー！
