### ISSUE TITLE
多言語対応のセットアップ

### ISSUE THREAD

**Issue by Haru-Kobayashi073** [KDG-Develop-Hub/social-mobile#9]
[このPR](https://github.com/Haru-Kobayashi073/search_github_repository_app/pull/9)を参考に進める
[この記事](https://qiita.com/myzw1mt3/items/8631d4615509119851a4)も参考にできる
SharedPreferencesを使用して、機種設定を保存し、watchする
@Haru-Kobayashi073 が詳しい説明をします

**Comment by aoiorio** [comment]
## Memo
- SharedPreferences使用しなくても良い
- ボタンを押すと言語が変わる設定をする
- riverpod_annotationをつける (Notifier を学ぶ)

**Comment by aoiorio** [comment]
![LGTM](https://raw.githubusercontent.com/yoshi389111/yoshi389111/main/LGTM/LGTM_github_contribute_light.png)
